name: Code quality

on:
    push:
        branches:
            - main
        paths:
            - src/**
    pull_request:
        paths:
            - src/**
    workflow_dispatch:
        inputs:
            php_version:
                description: 'Choose PHP version'
                required: false
                default: '8.2'

jobs:
    composer:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4
            -   uses: ./.github/actions/setup_php
                with:
                    php-version: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.php_version != '' && github.event.inputs.php_version || '8.2' }}


            -   name: Validate composer.json and composer.lock
                run: composer validate --strict

            -   name: Search for security vulnerabilities
                run: composer audit

            -   name: Check system requirements
                run: composer check

    code_quality:
        needs: [ 'composer' ]
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4
            -   uses: ./.github/actions/setup_php
                with:
                    php-version: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.php_version != '' && github.event.inputs.php_version || '8.2' }}


            -   name: Static analysis
                run: vendor/bin/phpstan analyze --error-format=github

            -   name: Code style
                run: vendor/bin/php-cs-fixer fix --dry-run --format=json

    test:
        needs: [ 'composer', 'code_quality' ]
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4
            -   uses: ./.github/actions/setup_php
                with:
                    php-version: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.php_version != '' && github.event.inputs.php_version || '8.2' }}

            -   name: Test
                run: vendor/bin/phpunit
